name: Publish Preview Package

on:
  push:
    branches:
      - fix/sti-child-relation-scoping-0.3.13
      - feat/class-table-inheritance-0.3.13

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 20

      - run: npm ci

      - run: npx gulp package

      - run: npx pkg-pr-new publish './build/package' --publicize
